### ISSUE TITLE
ios9 break bindKeyup() binding and live search not work on webapp anymore

### ISSUE THREAD

**Issue by ang3lx** [pawelczak/EasyAutocomplete#100]
i'm developing a little webapp with ios9/9.1 and EasyAutocomplete not work anymore in webview. Seems that there are some problem with keyup event

dirty workaround is to invert code of the two functions:
function bindKeypress() and function bindKeyup() 

here some info
http://gabert.ca/?p=51

is possible to patch this little thing?

**Comment by pawelczak** [comment]
Thanks for the info.

I've read a lot about this issue in the internet and I've tried couple of things to solve it. Unfortunately none of it worked fine. I'm sorry to hear about your problems, but for now I can't help. Only solutions is to wait for ios9 fix.
