### ISSUE TITLE
trigger change on enter (keycode 13) as well as click

### ISSUE THREAD

**Issue by tobybowers** [pawelczak/EasyAutocomplete#101]
Hi,
I'm loving the plugin and am using it for auto completion of addresses from postcode selection.
I'm using onClickEvent as onSelectItemEvent triggers even when hovering over an item.
What i'm looking to also make happen is the following:
When a user manually types the postcode and presses enter for it to trigger the selection of the matching item in the list.

Is this possible in some way?

**Comment by pawelczak** [comment]
Hey, 
I'm glad you like it. Can you send me some of your code:
- plugin options,
- sample data.

I need it to better understand your case.

**Comment by tobybowers** [comment]
Hi,
Thanks for the response.
As i said, i want to cater for selection via keyboard using arrow keys or manually typing the value and pressing enter as well as click.

I've used onClickEvent as i don't want the linked fields to change until the selection is made. Currently, if you use onSelectItemEvent the changes happen even if you just hover over the selection options.

My code is as follows:

var cityOptions = {
    data: [
        {
            "city":"Exloo",
            "code":"7875AA",
            "street": "Hoofdstraat"
        },
        {
            "city":"Exloo",
            "code":"7875BW",
            "street": "Zuiderhoofdstraat"
        }
    ],

    /*url: "resources/maps.json",*/
    minCharNumber: 2,
    getValue: function(element) {
        return element.city;
    },

    template: {
        type: "custom",

        method: function(value, item) {
            return "<div data-item-value='" + item.code + "' >" + value + " - " + item.code + "</div>";
        }
    },

    list: {
        match: {
            enabled: true
        },
        onClickEvent: function() {
            var selectedItemValue = $(".inputCity").find(".easy-autocomplete ul li.selected div[data-item-value]").attr("data-item-value");
            $(".inputZipCode").find(".easy-autocomplete ul li.selected").removeClass("selected");
            $("#application_add_zipCode").val(selectedItemValue).trigger("change");
        }
    }
};

var codeOptions = {
    data: [
        {
            "city":"Exloo",
            "code":"7875AA",
            "street": "Hoofdstraat"
        },
        {
            "city":"Exloo",
            "code":"7875BW",
            "street": "Zuiderhoofdstraat"
        }
    ],
    /*url: "resources/maps.json",*/
    minCharNumber: 2,
    getValue: function(element) {
        return element.code;
    },

    template: {
        type: "custom",
        method: function(value, item) {
            return "<div data-city-value='" + item.city + "' data-street-value='" + item.street + "'>" + value + " - " + item.city + "</div>";
        }
    },

    list: {
        match: {
            enabled: true
        },
        onClickEvent: function() {
            var selectedCityValue = $(".inputZipCode").find(".easy-autocomplete ul li.selected div[data-city-value]").attr("data-city-value");
            var selectedStreetValue = $(".inputZipCode").find(".easy-autocomplete ul li.selected div[data-street-value]").attr("data-street-value");
            $(".inputCity").find(".easy-autocomplete ul li.selected").removeClass("selected");
            $("#application_add_city").val(selectedCityValue).trigger("change");
            $("#application_add_street").val(selectedStreetValue).trigger("change");
        }
    }
};

$("#application_add_city").easyAutocomplete(cityOptions);
$("#application_add_zipCode").easyAutocomplete(codeOptions);

Best Regards,
Toby
________________________________

**Comment by pawelczak** [comment]
I've tested your code and I've came up with solution. There is a new way to trigger events: onHideListEvent. It triggers when user closes list so function is envoked, when user types enter and clicks on element. 
The one thing is that this event handler has not been released yet, so you need to download plugin version directly from github dist folder (https://github.com/pawelczak/EasyAutocomplete/blob/master/dist/jquery.easy-autocomplete.min.js).

Let me know if that helped you.

**Comment by tobybowers** [comment]
Hi Lukasz,


    That's great but it's lacking one thing. The ability to manually type in the entry without selecting something from the list.


I've managed to get all the functionality i needed by modifying the 1.1.5 code and i've attached my non-minified version.


What i've done might not be the best for all round compatibility, maybe you could refine it and use what you feel like.


I've added 2 new parameters:


adjustWidthProperty

manualEntry


the current plugin automatically adds a width to the container. This was causing a problem with my input fields as it was overriding some of the CSS. adjustWidthProperty allows you to disable the auto adjust.


manualEntry is used in bindKeyDown().

I've added the following if statement for keyDown()


if (event.keyCode === 13 && selectedElement === -1 && elementsList.length === 1)


This check when enter is pressed to see if no selection has been made and that there is only one selection available. If so, the item is selected and onClickEvent is fired.


I'm sure there's a better way to do this that can be used by any event trigger, maybe you'd like to do that and incorporate it for the next release.


Again, thanks for the plugin and your help.
I look forward to using it more in the future and do let me know if any of my additions are implemented correctly [😊]


Regards,
Toby

________________________________

**Comment by pawelczak** [comment]
Thanks Toby for great suggestion, I will definitely add it in the future.

I really appreciate creative ideas for this plugin.

**Comment by pawelczak** [comment]
Related to #110 #109
