### ISSUE TITLE
Category names appear for empty results

### ISSUE THREAD

**Issue by jeffcoughlin** [pawelczak/EasyAutocomplete#107]
I search from a remote datasource populated from a lucene search engine. Categories are great - thanks! When results are returned and some categories have no data, the menu/dropdown still has the categories (with no data). Can they be removed if they have no associated data returned from the source?

Problem example (The category name "Elements" should not be returned since it has no associated results):
-- Fruit --
Apple
Banana
-- Elements --
-- Countries --
Afghanistan
Albania

**Comment by pawelczak** [comment]
Duplicate #91.
I've released version 1.2.0, that contains #91 fix, so you can use it.

Thanks for reporting.
