### ISSUE TITLE
maxNumberOfElements not respected with categories for total results returned

### ISSUE THREAD

**Issue by jeffcoughlin** [pawelczak/EasyAutocomplete#108]
**Two issues that are both directly related**

**Issue 1:** When using categories (great feature!) the _maxNumberOfElements_ is not correct in the results because it is returned as max results per category/group. My advice would be to have a different parameter name like _maxNumberOfElementsPerCategory_.

Or if it's easier, add it as a parameter inside each category struct settings - giving the user more fine-grained control). Example: ```categories: [ {listLocation: ..., maxNumberOfElements: 3 } ]```

**Issue 2:** The bigger problem as it is now is that if a dataset has, say, 5 categories and each one has 10 matching results and you set maxNumberOfElements to 10, then instead of getting 10 results show, you get 50 because each category/group has a max of 10 (not the total results as you'd expect).

The main maxNumberOfElements really needs to lock down the total results as the user would expect so that the resultset doesn't get out of control.

**Comment by pawelczak** [comment]
Thanks Jeff for catchings these bugs, I'll fix them in nearest patch.
