### ISSUE TITLE
Reducing multiple request calls

### ISSUE THREAD

**Issue by tobybowers** [pawelczak/EasyAutocomplete#113]
Hi Lukasz,

To reduce the possibly excessive requests when using remote data/ajax and compliment matchResponseProperty i've added the following functionality that i thought i'd share with you.

I've added the following default configuration value:
getDataTimeout: 0,

This is then used within function bindKeyup() to delay the calling of loadData()
The default value is 0 i.e. disabled but can be set like any configuration values and will represent the number of milliseconds to delay the search. Each successive keypress within the delay time will reset the delay before triggering loadData.

Within bindKeyup() i've added var timeoutID; at the top of the function and changed the following from:

default:
   if (event.keyCode > 40 || event.keyCode === 8) {
      loadData();
   }
   break;

to

default:
  if (event.keyCode > 40 || event.keyCode === 8) {
    if(config.get("getDataTimeout") != 0){
        clearTimeout(timeoutID);
        timeoutID = setTimeout(loadData, config.get("getDataTimeout"));
     } else {
        loadData();
     }
  }
  break;

I hope you like the changes and will think about adding them.

**Comment by pawelczak** [comment]
I really like your idea. I'll definitely add your code. The only issue is that it will not be easy to test this feature. So it can take me couple of day before I'll add your code. But don't be worry, thanks for your help.
