### ISSUE TITLE
Send input value in ajax post data

### ISSUE THREAD

**Issue by tobybowers** [pawelczak/EasyAutocomplete#118]
Hi Lukasz,

Here's another little addition i've made to my version (i really need to start doing this in a branch).

This addition allows for when a user requires to send the input value as part of the ajax post data (not the get data as is the current option).

Added to scope.Configuration:
ajaxPostFieldVal: "none",

Default value set to string "none" as opposed to boolean false as this causes issues when assigning a value below. The value assigned to ajaxPostFieldVal will be used as the post data key.

Added to function loadData() below
if (settings.dataType === undefined || settings.dataType === "") {
							settings.dataType = config.get("dataType");
						}

New addition:

// check if inputPhase is required in Post Data
                        if (config.get("ajaxPostFieldVal") !== "none"){
                            settings.data[config.get("ajaxPostFieldVal")] = inputPhrase;
                        }

**Comment by pawelczak** [comment]
Your solution is quite clever, but I need to think about it. It feels kind like a hack, which I don't want to introduce. 

This issue with post data should be resolved in simple and intuitive way.

Another problem with your solution is what if user want to add two dynamic data sources one from text inputA and other from text inputB. It can't be done this way.

**Comment by tobybowers** [comment]
Good point, my solution was only for the field entered in.
