### ISSUE TITLE
Match option not working with AJAX source

### ISSUE THREAD

**Issue by andybellenie** [pawelczak/EasyAutocomplete#121]
My code:

```
var options = {
	url: function(phrase) {
		return "/ajax/search?phrase="+phrase;
	},
	list: {
		match: {
			enabled: true
		}
	}
};
$("#search_input").easyAutocomplete(options);
```

When the ajax request returns an empty array (no results found), I expect to see the dropdown of options disappear, but it doesn't.
![screen shot 2015-11-05 at 21 51 42](https://cloud.githubusercontent.com/assets/147703/10982831/7500a8d8-8407-11e5-9420-19a5de9ee185.png)

**Comment by pawelczak** [comment]
Thank for report, I'll try to fix this issue as soon as possible.

**Comment by andybellenie** [comment]
Works great thank you for the amazingly fast response :+1:
