### ISSUE TITLE
automatic width adjustment  

### ISSUE THREAD

**Issue by nineonine** [pawelczak/EasyAutocomplete#125]
That took me a while to figure out how to disable that adjustWidth thing . 

Is there a special necessity for this configuration ?

Cheers

**Comment by pawelczak** [comment]
I've never thought about necessity of this option, I'll need to look into this. Thanks for pointing out this problem.

**Comment by pawelczak** [comment]
This parameter is need to be true on default, so items list can be same width as input text. This option should be described in the website guide.
