### ISSUE TITLE
Last version in bower is not updated

### ISSUE THREAD

**Issue by cesco69** [pawelczak/EasyAutocomplete#127]
Last available version of easyautocomplete in bower is 1.1.6
The command to see this is: bower info EasyAutocomplete

**Comment by pawelczak** [comment]
Thanks !

**Comment by pawelczak** [comment]
I'm straggling with this issue. How to let bower know that there is new version of the plugin?

**Comment by cesco69** [comment]
Npm gives the same bower result... 
I found this guide https://viget.com/extend/publishing-packages-to-npm-and-bower 
In the last part shows how to update to Npm and bower

**Comment by cesco69** [comment]
Another article detailed on update https://viget.com/extend/an-update-on-updating-npm-and-bower-packages

**Comment by pawelczak** [comment]
Thanks for help, bower shows correct version now.
I need to remember, that i should run this commands after release:
``
npm publish
git push --tags
``

**Comment by cesco69** [comment]
Another issue, installing version 1.3.1 downloads 1.3.0

**Comment by pawelczak** [comment]
Yeah i know about this one. It's a bug, distribution files shows tags from previous versions. The content of the files is up to date, only version tag is bad. I'll fix it in next release.

Once again thanks for reporting :+1: . If you see more issues let me know.
