### ISSUE TITLE
Bootstrap modal events are triggered unexpectedly

### ISSUE THREAD

**Issue by CodeReaper** [pawelczak/EasyAutocomplete#139]
When using bootstrap modals with an autocomplete field inside, there seems to be an issue with event namespacing. 

In `core.js` the `showContainer()` function triggers the event "show" which bubbles up and triggers the "show.bs.modal" event too.

###### Example / Workaround
```javascript
$("#myModal").on('show.bs.modal', function (e) {
        if ($(e.relatedTarget).is(":not(.easy-autocomplete-container)")) {
                // events not triggered by EasyAutocomplete
        }
}
```
For now I will continue to use my workaround...

**Comment by pawelczak** [comment]
Plugin specific event names should be renamed with sufix ".eac"
