### ISSUE TITLE
How do i use easy-complete with elasticsearch ?

### ISSUE THREAD

**Issue by thisismyaim** [pawelczak/EasyAutocomplete#152]
Using this code :

         $(function () {
              var options = {
                url: function(phrase) {
                    return "/api/search";
                },

                getValue: function(element) {
                    console.log(element.hits);
                },

                ajaxSettings: {
                    dataType: "json",
                    method: "POST",
                    data: {
                        dataType: "jsonp",
                        "_token": "{{ csrf_token() }}"
                    }
                },

                preparePostData: function(data) {
                    data.query = $("#search").val();
                    return data;
                },

                requestDelay: 400
            };

            $("#search").easyAutocomplete(options);
        });

But nothing shows in console log - i think something should be in console so i can get the data

**Comment by pawelczak** [comment]
Can you show an example of json response data?

**Comment by thisismyaim** [comment]
Here is output data

{
    "took": 5,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "failed": 0
    },
    "hits": {
        "total": 53,
        "max_score": 0.2795286,
        "hits": [{
            "_index": "yourservice",
            "_type": "categories",
            "_id": "AVE4woX4L3xK7ne9Wqve",
            "_score": 0.2795286,
            "_source": {
                "name": "Home Automation ",
                "title": " Home Automation | Your Service Connection",
                "description": "Automate your life",
                "subcategories": "Lightning",
                "suggested_tags": ["led home lighting"]
          }

**Comment by thisismyaim** [comment]
jQuery Code i am using for autocomplete :

```javascript
// jQuery Code i used
                    success: function(data) {
                            $(".glyphicon-search").removeClass('fa fa-circle-o-notch fa-spin');
                            response($.map(data.hits.hits, function(item) {
                                var v = item._source['title'];
                                var w;
                                if( Object.prototype.toString.call(v) === '[object Array]' ) {
                                    v.map(function(element, index, array) {
                                        for (var i in element) {
                                            if (element.hasOwnProperty(i)) {
                                                w = w ? w + " / " + element[i] :element[i];
                                            }
                                        }
                                    })
                                }
                                var label =
                                        (w ? w : item._source['name']);

                                return {
                                    label: item._source['name'],
                                    value: label
                                }
                            }));
                        }

**Comment by pawelczak** [comment]
Eac plugin shows list of elements as autocomplete list. In order to work correctly, plugin needs an array of elements, so you need to specifie where this array is located in response data.

Your response data is complex, so you need to use option listLocation (http://easyautocomplete.com/guide#sec-list-location). 

I assumed, that you want to use array "hits" as autocomplete list, add this property to options:
```listLocation: function(data) {return data["hits"]["hits"];}```

Another thing is that array "hits" contains objects, so you need to decide what value you want to show on autocomplete list. I've selected "_source.name":
```getValue: function(element) {return element["_source"]["name"];}```

I guess this code should work:
```
$(function () {
      var options = {
        url: function(phrase) {
            return "/api/search";
        },

        listLocation: function(data) {
            return data["hits"]["hits"];
        },

        getValue: function(element) {
            return element["_source"]["name"];
        },

        ajaxSettings: {
            dataType: "json",
            method: "POST",
            data: {
                dataType: "jsonp",
                "_token": "{{ csrf_token() }}"
            }
        },

        preparePostData: function(data) {
            data.query = $("#search").val();
            return data;
        },

        requestDelay: 400
    };

    $("#search").easyAutocomplete(options);
});
```

**Comment by thisismyaim** [comment]
Thanks, it's working as you said..

**Comment by Maanasa435** [comment]
Can we use both url and data in a single function. My requirement is Whenever input length is 4, url call should be made and after 4, that data should get filtered in js only. i.e., data should be stored when url call is made
