### ISSUE TITLE
Auto-generate categories?

### ISSUE THREAD

**Issue by Dr-Mx** [pawelczak/EasyAutocomplete#212]
Hi pawelczak,

Is there a way to auto-generate the 'categories' option for all items found in data?
I'm duplicating a lot of information in both 'listlocation' and 'header', which will need to be rewritten if I change the data.

Also, is there a way to capture a clicked item's category, and put it into a variable?

Many thanks for your time.

**Comment by pawelczak** [comment]
Remeber that almost everything is an object in javascript, so you can do something like that:

```javascript
var category = {
        listLocation: "marvel",
        maxNumberOfElements: 4,
        header: "Marvel - heroes"
    },
    catOne = category,
    catTwo = category;

catOne.header = 'Header one';
catTwo.header = 'Header two';

var options = {
    categories: [
        catOne, 
        catTwo
    ],
    ...
};
```

For second question, did you try onClickEvent? Here you can find more about it:
http://easyautocomplete.com/guide#sec-trigger-event
http://easyautocomplete.com/example/select-event

**Comment by Dr-Mx** [comment]
Ah great, thanks.  That makes sense.

I've put all my categories into an array now.  Is there a way of looping though them within the options var so I don't have to type category[0], category[1], category[2]...etc ?

Apologies if all this stuff is obvious, I'm quite new to JS :)
Cheers.

**Comment by Dr-Mx** [comment]
No worries I got it:
```
var x = 1;
for (x = 1; x < category.length; x++) {
   options["categories"].push(category[x]);
}
```
