### ISSUE TITLE
Continue to do autocomplete after word is chosen

### ISSUE THREAD

**Issue by jarnstad** [pawelczak/EasyAutocomplete#224]
I have a case where I'm using ajax to provide autocomplete data. But if a keyword is chosen from the list, autocomplete stops until i press backspace. Space doesn't trigger autocomplete. 
I'm changing the json based on the keyword, so when a keyword matches one in the json, I use that to generate a new json with the first keyword an add a new keyword behind with space as a divider. 

first json used
{'name':'keyword11'}
{'name':'keyword12'}
{'name':'keyword13'}
{'name':'keyword14'}

second json used
{'name','keyword1 keyword21'}
{'name','keyword1 keyword22'}
{'name','keyword1 keyword23'}

so auto complete will show keyword1* first and when one is chosen, then it will show keyword1* keyword2*

if i just write the whole word the autocomplete works
![screen shot 2016-08-08 at 16 26 18](https://cloud.githubusercontent.com/assets/2228755/17483077/e55b73c2-5d84-11e6-8119-09ebe0794578.png)
![screen shot 2016-08-08 at 16 26 31](https://cloud.githubusercontent.com/assets/2228755/17483076/e5578ba4-5d84-11e6-90f1-94e8fba53846.png)

**Comment by jarnstad** [comment]
Soved

**Comment by pritishjoshi94** [comment]
can you explain how ??
