### ISSUE TITLE
[Question] Is there any way to programmatically reset a field?

### ISSUE THREAD

**Issue by jpmurray** [pawelczak/EasyAutocomplete#246]
Say I have to easyautocomplete field, and on one's onChooseEvent() I want to be able to reset/empty the second one's data.

Anyway to accomplish this?

**Comment by nckblu** [comment]
Is it not just a case of `$(input#yourInput).val('') `or are you trying to achieve something different?

**Comment by jpmurray** [comment]
@nckblu Let's see.

I have two autocomplete field. The first one decides what kind of source is in the second. So when I choose something in the first, the second one should "reset" so I can make an entire new search from it. I know I've tried `val('')`ing the input of the second search field, but the visible search field stayed the same. 

At this point, I'm actually thinking I should remove and recreate the second field `onChooseEvent()`, unless there is an easier way!

**Comment by nckblu** [comment]
`val()` should work in that case, do you want to post your code including how you're doing the `val()`

**Comment by jpmurray** [comment]
Welp,

For whatever reason, I rewrote the part of the script so I could post it and it'd be cleaner to read... And now it works. I must have made a stupid mistake somewhere... Thanks for being my [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging), I guess! :D
