### ISSUE TITLE
Don't search until user types 3 or more characters

### ISSUE THREAD

**Issue by rdgupt** [pawelczak/EasyAutocomplete#293]
Hi,

I don't want to trigger search request to server until user has typed min 3 characters in input field.
How do I do it?

Thanks.

**Comment by hosein2398** [comment]
@rdgupt 
You can do : 
```
<input id="basics" />
```
Js:
```
var options = {
	url: "resources/countries.json",
	getValue: "name",
	list: {
		match: {
			enabled: true
		}
	}
};

document.getElementById("basics").addEventListener("input", function (e) {
   if(this.value.length > 3){
	   $("#basics").easyAutocomplete(options);
   }
});
```
And consider input tag styles before and after adding the plugin to that , change them yourself.

**Comment by rdgupt** [comment]
Sorry, but I don't think it solves it. Until user types 4 characters easyAutocomplete is not enabled, but once it is set on the input box then user goes back to 1 char it still sends the request to server.

**Comment by smarques** [comment]
try setting minCharNumber in your options. Don't know why this is not documented. Works for me.

**Comment by rdgupt** [comment]
THANK YOU!!

minCharNumber works.
My bad, I could have checked in source code.
