### ISSUE TITLE
Click on list scrollbar and list window closes.

### ISSUE THREAD

**Issue by gbfromhb** [pawelczak/EasyAutocomplete#302]
I need a vertical scrollbar on the list window. I'm using a custom list template. I used the following CSS and it works up to a certain point.

.easy-autocomplete-container {
   max-height: 300px;
   overflow-y: auto;
}

The wheel on the top of the mouse will scroll the list just fine, but when I click on the scrollbar, to scroll it by dragging the mouse up and down the list window closes.

Any suggestions?

**Comment by gbfromhb** [comment]
I just realized it is a Internet Explorer 11 issue. Chrome and Edge are working fine.

**Comment by igorlovric** [comment]
I use similar CSS, and I had same issue, but not just in IE,... for me it closes in all browsers.

I solved it this way:

In **jquery.easy-autocomplete.js**, find function **createContainer()**, and on the end of function, just before **$field.after($elements_container);** line, add fallowing code:

```
$elements_container.mousedown(function (e) {
     if($(this).outerWidth() < e.clientX){ e.preventDefault(); }
})
```

Also, there is one more problem regarding this CSS. If you use Up/Down arrows to chose item, container doesn't scroll when you reach bottom of container.

To solve this, find **bindKeyup()** function, you'll see there is CASE for each of arrow buttons (Code 38, and Code 40), for both of those keys, just after line: **selectElement(selectedElement);** add fallowing code:

```
$('#'+getContainerId()+' ul li.selected')[0].scrollIntoView({
     behavior: "smooth",
     block: "start"
});
```

**Comment by gbfromhb** [comment]
Thanks igorlovric.

**Comment by skkanagaraj** [comment]
I have tried above code. While I click vertical scrollbar using mouse pointer. The easy-autocomplete-container 'Div' style was changed as below

i.e) style='Display:none'.

so, the easyautocomplete was hidden on every click in scrollbar.

**Comment by hejdujir** [comment]
Best solution for me is
`function bindBlur() {
				$field.blur(function() {
if (!$(document.activeElement).hasClass('easy-autocomplete-container')) {
					setTimeout(function() { 
						selectedElement = -1;
						hideContainer();
					}, 250);
}else{
$field.focus();
}
				});
			}`
