### ISSUE TITLE
EasyAutocomplete not working properly on firefox quantum 63.0.1 (32-bit)

### ISSUE THREAD

**Issue by montyrejack** [pawelczak/EasyAutocomplete#375]
I've been using easyAutocomplete for several months now, but suddenly it stopped working.
When i type nothing happens. Only when i use backspace the autocomplete list pops up.

**Comment by amiga-500** [comment]
Works fine in 64.x (64-bit).  Just in case, can: _History > Show All History > (locate the site that uses Autocomplete) > Right-click > Forget this Site_

Then navigate back to the site and check to see if Autocomplete is still not working

**Comment by montyrejack** [comment]
Found the problem. And had nothing to do with firefox. I was working on remote desktop and for some reason when typing every key was registered with keycode 0
