### ISSUE TITLE
easyAutocomplete is not a function

### ISSUE THREAD

**Issue by vincent-dp** [pawelczak/EasyAutocomplete#398]
I have jquery included within the <head> tag

And then, I have this in my <body> (I know, not the best practice, but for my CMS usage purpose, it's easier for me)

`<script src="jquery.easy-autocomplete.min.js"></script>`
`<script>`
`$(document).ready(function(){`
        `var options = {`
            `url: "villes_france.json"`
        `};`
   ` $("#city-search").easyAutocomplete(options);`
`});`
`</script>`

The urls are good and tested

When I load my page, I have the error I put in the title

> $(...).easyAutocomplete is not a function

**Comment by aungooaung** [comment]
You need to include jqueryui.
