### ISSUE TITLE
Will not sort alphanumeric combinations

### ISSUE THREAD

**Issue by shayster01** [pawelczak/EasyAutocomplete#61]
First of all thanks for this. Unless I missed something, I used your example for emails and reversed the display. Where it list the email( has fuzzy text) first and then the name. My sql query checks to see if the name or email matches the term. Have tested the query and it works but it will only display up until it reaches a number in the email address.

**Comment by pawelczak** [comment]
I'm trying to create same example as you've describe, but I'm somehow  not able to do it. I mean, for me your example works fine. I guess, I'm not recreating it to match your case. Can you paste some of your code: 
- plugin options,
- sample data - json/xml.
